In [40]:
import pandas as pd

data=pd.read_csv('lego_sets.csv')
data.head(30)
#data clean 
data=data.dropna(subset="set_num")
data.head(20)

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space
5,0014-1,Space Mini-Figures,1979,12.0,Supplemental,Space
6,0015-1,Space Mini-Figures,1979,NaN,Supplemental,Space
7,0016-1,Castle Mini Figures,1978,NaN,Castle,Castle
8,00-2,Weetabix Promotional House 1,1976,NaN,Building,Legoland
9,00-3,Weetabix Promotional House 2,1976,NaN,Building,Legoland
10,00-4,Weetabix Promotional Windmill,1976,126.0,Building,Legoland
11,005-1,Basic Building Set in Cardboard,1965,35.0,Basic Set,Classic
12,00-6,Special Offer,1985,3.0,Classic Town,Town
13,00-7,Weetabix Promotional Lego Village,1976,NaN,Building,Legoland
14,010-1,Basic Building Set in Cardboard,1965,57.0,Basic Set,Classic
15,010-3,Basic Building Set,1968,77.0,Basic Set,Classic
16,011-1,Basic Building Set,1968,145.0,Basic Set,Classic
17,022-1,Basic Building Set,1968,110.0,Basic Set,Classic
18,03093-1,The Race to Build It Board Game,1999,NaN,Game,Gear
19,033-2,Basic Building Set,1968,NaN,Basic Set,Classic

In [41]:
count_row = data.shape[0]
print(count_row)

11833

In [45]:

data.loc[data['parent_theme'] == 'Star Wars']

,set_num,name,year,num_parts,theme_name,parent_theme
44,10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars
45,10019-1,Rebel Blockade Runner - UCS,2001,NaN,Star Wars Episode 4/5/6,Star Wars
54,10026-1,Naboo Starfighter - UCS,2002,NaN,Star Wars Episode 1,Star Wars
57,10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars
116,10123-1,Cloud City,2003,707.0,Star Wars Episode 4/5/6,Star Wars
...,...,...,...,...,...,...
11811,VP-12,Star Wars Co-Pack of 7121 and 7151,2000,2.0,Star Wars Episode 1,Star Wars
11816,VP-2,Star Wars Co-Pack of 7110 and 7144,2001,2.0,Star Wars Episode 4/5/6,Star Wars
11817,VP-3,Star Wars Co-Pack of 7131 and 7151,2000,2.0,Star Wars Episode 1,Star Wars
11818,VP-4,Star Wars Co-Pack of 7101 7111 and 7171,2000,3.0,Star Wars Episode 1,Star Wars
11822,VP-8,Star Wars Co-Pack of 7130 and 7150,2000,NaN,Star Wars Episode 4/5/6,Star Wars

In [47]:
theme=pd.read_csv('parent_themes.csv')

theme.head(50)

     id                      name  is_licensed
0     1                   Technic        False
1    22                   Creator        False
2    50                      Town        False
3   112                    Racers        False
4   126                     Space        False
5   147                   Pirates        False
6   155         Modular Buildings        False
7   158                 Star Wars         True
8   186                    Castle        False
9   204             Designer Sets        False
10  206                  Seasonal        False
11  233                     Train        False
12  246              Harry Potter         True
13  252              Architecture        False
14  254               Bulk Bricks        False
15  258                Mindstorms        False
16  263  Pirates of the Caribbean         True
17  264             Indiana Jones         True
18  269                      Cars         True
19  270                    Ben 10         True
20  271          Prince of Persia         True
21  272     SpongeBob SquarePants         True
22  273                   Studios        False
23  275                 Toy Story         True
24  276                Sculptures        False
25  278                Model Team        False
26  279                 4 Juniors        False
27  296               Adventurers        False
28  301                     Other        False
29  302                    Agents        False
30  304                Alpha Team        False
31  307                  Aquazone        False
32  315                  Atlantis        False
33  317                    Avatar         True
34  318                  Belville        False
35  324                  Bionicle        False
36  363                      Boat        False
37  364  Building Set with People        False
38  365                   Classic        False
39  384                 Dino 2010        False
40  385               Dino Attack        False
41  386                 Dinosaurs        False
42  387                 Discovery        False
43  388     Disney's Mickey Mouse         True
44  389                 Exo-Force        False
45  390                  Fabuland        False
46  397                   Factory        False
47  398         FIRST LEGO League        False
48  399                 Freestyle        False
49  400              Hero Factory        False

# 1.What percentage of all licensed sets ever released where star war themed?
### first merge two sheets
### find total that have license
### then find how many star war licensed
### then find the percentage of star wars in licensed

In [52]:
merged=data.merge(theme, left_on='parent_theme', right_on='name')

merged.head(50)

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,name_y,is_licensed
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland,411,Legoland,False
1,00-2,Weetabix Promotional House 1,1976,NaN,Building,Legoland,411,Legoland,False
2,00-3,Weetabix Promotional House 2,1976,NaN,Building,Legoland,411,Legoland,False
3,00-4,Weetabix Promotional Windmill,1976,126.0,Building,Legoland,411,Legoland,False
4,00-7,Weetabix Promotional Lego Village,1976,NaN,Building,Legoland,411,Legoland,False
5,102A-1,Front-End Loader,1970,64.0,Construction,Legoland,411,Legoland,False
6,102A-2,Front-End Loader,1970,NaN,Construction,Legoland,411,Legoland,False
7,1-10,Mini-Wheel Model Maker No. 1,1971,88.0,Vehicle,Legoland,411,Legoland,False
8,1550-1,Sterling Super Caravelle,1972,NaN,Airport,Legoland,411,Legoland,False
9,1551-2,Sterling Luggage Carrier,1972,49.0,Airport,Legoland,411,Legoland,False
10,1552-2,Sterling Boeing 727,1974,45.0,Airport,Legoland,411,Legoland,False
11,1555-2,Sterling Airways Biplane,1978,NaN,Airport,Legoland,411,Legoland,False
12,1560-2,Lufthansa Boeing 727,1976,44.0,Airport,Legoland,411,Legoland,False
13,1562-3,Lufthansa Double-Decker,1976,NaN,Airport,Legoland,411,Legoland,False
14,157-3,Four Car Auto Transport,1970,NaN,Vehicle,Legoland,411,Legoland,False
15,1601-1,Conveyance,1976,NaN,Construction,Legoland,411,Legoland,False
16,1610-2,Martinair Cessna,1978,82.0,Airport,Legoland,411,Legoland,False
17,1611-2,Martinair DC-9,1978,63.0,Airport,Legoland,411,Legoland,False
18,2-10,Mini-Wheel Model Maker No. 2,1971,63.0,Vehicle,Legoland,411,Legoland,False
19,248-2,Factory With Conveyor Belt,1971,208.0,Construction,Legoland,411,Legoland,False
20,338-1,Ambulance,1970,74.0,Hospital,Legoland,411,Legoland,False
21,344-1,Bungalow,1969,77.0,Building,Legoland,411,Legoland,False
22,345-1,House with Mini Wheel Car,1969,132.0,Building,Legoland,411,Legoland,False
23,346-1,Jumbo Jet,1970,NaN,Airport,Legoland,411,Legoland,False
24,346-2,House with Car,1969,167.0,Building,Legoland,411,Legoland,False
25,347-1,Fire Station with Mini Cars,1970,205.0,Fire,Legoland,411,Legoland,False
26,348-1,Garage with Automatic Doors,1971,38.0,Building,Legoland,411,Legoland,False
27,349-1,Swiss Chalet,1971,81.0,Building,Legoland,411,Legoland,False
28,350-1,Spanish Villa,1971,126.0,Building,Legoland,411,Legoland,False
29,351-1,Loader Hopper with Truck,1971,170.0,Construction,Legoland,411,Legoland,False
30,352-1,Windmill and Lorry,1972,142.0,Building,Legoland,411,Legoland,False
31,353-1,Terrace House with Car and Garage,1972,153.0,Building,Legoland,411,Legoland,False
32,354-1,Police Heliport,1972,173.0,Police,Legoland,411,Legoland,False
33,355-1,Town Center Set with Roadways,1972,NaN,Building,Legoland,411,Legoland,False
34,356-1,Swiss Villa,1973,NaN,Building,Legoland,411,Legoland,False
35,357-1,Fire Station,1973,236.0,Fire,Legoland,411,Legoland,False
36,358-1,Rocket Base,1973,276.0,Space,Legoland,411,Legoland,False
37,360-1,Gravel Quarry,1974,211.0,Construction,Legoland,411,Legoland,False
38,361-1,Tea Garden Cafe with Baker's Van,1974,214.0,Building,Legoland,411,Legoland,False
39,362-1,Windmill,1975,NaN,Building,Legoland,411,Legoland,False
40,363-1,Hospital with Figures,1975,NaN,Hospital,Legoland,411,Legoland,False
41,364-1,Harbour Scene,1975,515.0,Harbor,Legoland,411,Legoland,False
42,367-1,Moon Landing,1975,363.0,Space,Legoland,411,Legoland,False
43,368-1,Taxi Station,1976,157.0,Building,Legoland,411,Legoland,False
44,369-1,Coast Guard Station,1976,NaN,Coast Guard,Legoland,411,Legoland,False
45,370-1,Police Headquarters,1976,300.0,Police,Legoland,411,Legoland,False
46,371-1,Tipper Truck,1971,47.0,Construction,Legoland,411,Legoland,False
47,371-3,Seaplane,1977,NaN,Airport,Legoland,411,Legoland,False
48,373-1,Offshore Rig with Fuel Tanker,1977,NaN,Gas Station,Legoland,411,Legoland,False
49,373-2,Ambulance,1971,65.0,Hospital,Legoland,411,Legoland,False

In [56]:
licensed=merged[merged['is_licensed']]
licensed.head(50)
count_license=licensed.shape[0]
print(count_license)

1179

In [60]:
starwars=licensed[licensed['parent_theme']=='Star Wars']
starwars.head(50)
count_star=starwars.shape[0]
print(count_star)

609

In [62]:
percent=int((count_star/count_license)*100)
print (percent)

51

### 1.What percentage of all licensed sets ever released where star war themed?
### 51

# 2. In which year was Star wars not the most famous licensed theme(In terms of number of themes released that year)? 
### first group the licensed data with year and parent_theme
### sum the data to use 'is_licensed' to use as total count
### sort and drop duplicates to find maximum in each year

In [97]:
licensed=licensed.sort_values(by=['year'])

In [110]:

sorted_data=licensed.groupby(['year','parent_theme'])
sorted_data=sorted_data.sum(numeric_only=True).reset_index()
# sorted 'is_licensed to find max'
find_max=sorted_data.sort_values('is_licensed', ascending=False)
#drop duplicates to find max in every year
find_max.drop_duplicates('year')

    year  parent_theme  num_parts     id  is_licensed
82  2017  Super Heroes    13123.0  34704           72
76  2016     Star Wars     6934.0   9638           61
67  2015     Star Wars    11410.0   9164           58
59  2014     Star Wars     8293.0   7110           45
47  2012     Star Wars     6769.0   6794           43
32  2009     Star Wars     3953.0   6162           39
52  2013     Star Wars     6159.0   5530           35
9   2003     Star Wars     6660.0   5056           32
42  2011     Star Wars     3451.0   5056           32
36  2010     Star Wars     6003.0   4740           30
16  2005     Star Wars     4730.0   4424           28
6   2002     Star Wars     4735.0   4424           28
2   2000     Star Wars     2580.0   4108           26
28  2008     Star Wars     6865.0   3634           23
12  2004     Star Wars     1659.0   3160           20
24  2007     Star Wars    11361.0   2528           16
4   2001     Star Wars     2949.0   2212           14
0   1999     Star Wars     1384.0   2054           13
20  2006     Star Wars     2769.0   1738           11

In [111]:
Year_StarWars_Not_Maximum=2017

### 2. In which year was Star wars not the most famous licensed theme(In terms of number of themes released that year)?
### 2017